package isamm.projet.beans;
// Generated 19 nov. 2017 20:44:16 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name = "etudiant", catalog = "bdhibernate_lasttp")
public class Etudiant implements java.io.Serializable {

	private int idPersonne;
	private int idFiliere;
	private String cne;

	public Etudiant() {
	}

	public Etudiant(int idPersonne, int idFiliere) {
		this.idPersonne = idPersonne;
		this.idFiliere = idFiliere;
	}

	public Etudiant(int idPersonne, int idFiliere, String cne) {
		this.idPersonne = idPersonne;
		this.idFiliere = idFiliere;
		this.cne = cne;
	}

	@Id

	@Column(name = "idPersonne", unique = true, nullable = false)
	public int getIdPersonne() {
		return this.idPersonne;
	}

	public void setIdPersonne(int idPersonne) {
		this.idPersonne = idPersonne;
	}

	@Column(name = "idFiliere", nullable = false)
	public int getIdFiliere() {
		return this.idFiliere;
	}

	public void setIdFiliere(int idFiliere) {
		this.idFiliere = idFiliere;
	}

	@Column(name = "cne", length = 254)
	public String getCne() {
		return this.cne;
	}

	public void setCne(String cne) {
		this.cne = cne;
	}

}
