package isamm.projet.beans;
// Generated 19 nov. 2017 22:25:43 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Filiere generated by hbm2java
 */
@Entity
@Table(name = "filiere", catalog = "bdhibernate_lasttp")
public class Filiere implements java.io.Serializable {

	private Integer idFiliere;
	private String code;
	private String libelle;

	public Filiere() {
	}

	public Filiere(String code, String libelle) {
		this.code = code;
		this.libelle = libelle;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idFiliere", unique = true, nullable = false)
	public Integer getIdFiliere() {
		return this.idFiliere;
	}

	public void setIdFiliere(Integer idFiliere) {
		this.idFiliere = idFiliere;
	}

	@Column(name = "code", length = 254)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libelle", length = 254)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
