package isamm.projet.beans;
// Generated 20 nov. 2017 01:22:30 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filiere generated by hbm2java
 */
@Entity
@Table(name = "filiere", catalog = "bdhibernate_lasttp")
public class Filiere implements java.io.Serializable {

	private Integer idFiliere;
	private String code;
	private String libelle;
	private Set<Lignematierefiliere> lignematierefilieres = new HashSet<Lignematierefiliere>(0);
	private Set<Etudiant> etudiants = new HashSet<Etudiant>(0);

	public Filiere() {
	}

	public Filiere(String code, String libelle, Set<Lignematierefiliere> lignematierefilieres,
			Set<Etudiant> etudiants) {
		this.code = code;
		this.libelle = libelle;
		this.lignematierefilieres = lignematierefilieres;
		this.etudiants = etudiants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idFiliere", unique = true, nullable = false)
	public Integer getIdFiliere() {
		return this.idFiliere;
	}

	public void setIdFiliere(Integer idFiliere) {
		this.idFiliere = idFiliere;
	}

	@Column(name = "code", length = 254)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libelle", length = 254)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filiere")
	public Set<Lignematierefiliere> getLignematierefilieres() {
		return this.lignematierefilieres;
	}

	public void setLignematierefilieres(Set<Lignematierefiliere> lignematierefilieres) {
		this.lignematierefilieres = lignematierefilieres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filiere")
	public Set<Etudiant> getEtudiants() {
		return this.etudiants;
	}

	public void setEtudiants(Set<Etudiant> etudiants) {
		this.etudiants = etudiants;
	}

}
