package isamm.projet.beans;
// Generated 19 nov. 2017 20:44:16 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LignematierefiliereId generated by hbm2java
 */
@Embeddable
public class LignematierefiliereId implements java.io.Serializable {

	private int idMatiere;
	private int idFiliere;
	private int idMatfiliere;

	public LignematierefiliereId() {
	}

	public LignematierefiliereId(int idMatiere, int idFiliere, int idMatfiliere) {
		this.idMatiere = idMatiere;
		this.idFiliere = idFiliere;
		this.idMatfiliere = idMatfiliere;
	}

	@Column(name = "idMatiere", nullable = false)
	public int getIdMatiere() {
		return this.idMatiere;
	}

	public void setIdMatiere(int idMatiere) {
		this.idMatiere = idMatiere;
	}

	@Column(name = "idFiliere", nullable = false)
	public int getIdFiliere() {
		return this.idFiliere;
	}

	public void setIdFiliere(int idFiliere) {
		this.idFiliere = idFiliere;
	}

	@Column(name = "idMatfiliere", nullable = false)
	public int getIdMatfiliere() {
		return this.idMatfiliere;
	}

	public void setIdMatfiliere(int idMatfiliere) {
		this.idMatfiliere = idMatfiliere;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LignematierefiliereId))
			return false;
		LignematierefiliereId castOther = (LignematierefiliereId) other;

		return (this.getIdMatiere() == castOther.getIdMatiere()) && (this.getIdFiliere() == castOther.getIdFiliere())
				&& (this.getIdMatfiliere() == castOther.getIdMatfiliere());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMatiere();
		result = 37 * result + this.getIdFiliere();
		result = 37 * result + this.getIdMatfiliere();
		return result;
	}

}
