package isamm.projet.beans;
// Generated 20 nov. 2017 01:22:30 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Lignematierefiliere generated by hbm2java
 */
@Entity
@Table(name = "lignematierefiliere", catalog = "bdhibernate_lasttp")
public class Lignematierefiliere implements java.io.Serializable {

	private Integer idMatfiliere;
	private Filiere filiere;
	private Matiere matiere;
	private Integer masseHoraire;

	public Lignematierefiliere() {
	}

	public Lignematierefiliere(Filiere filiere, Matiere matiere) {
		this.filiere = filiere;
		this.matiere = matiere;
	}

	public Lignematierefiliere(Filiere filiere, Matiere matiere, Integer masseHoraire) {
		this.filiere = filiere;
		this.matiere = matiere;
		this.masseHoraire = masseHoraire;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMatfiliere", unique = true, nullable = false)
	public Integer getIdMatfiliere() {
		return this.idMatfiliere;
	}

	public void setIdMatfiliere(Integer idMatfiliere) {
		this.idMatfiliere = idMatfiliere;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFiliere", nullable = false)
	public Filiere getFiliere() {
		return this.filiere;
	}

	public void setFiliere(Filiere filiere) {
		this.filiere = filiere;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMatiere", nullable = false)
	public Matiere getMatiere() {
		return this.matiere;
	}

	public void setMatiere(Matiere matiere) {
		this.matiere = matiere;
	}

	@Column(name = "masseHoraire")
	public Integer getMasseHoraire() {
		return this.masseHoraire;
	}

	public void setMasseHoraire(Integer masseHoraire) {
		this.masseHoraire = masseHoraire;
	}

}
