package isamm.projet.beans;
// Generated 19 nov. 2017 20:44:16 by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Lignematierefiliere generated by hbm2java
 */
@Entity
@Table(name = "lignematierefiliere", catalog = "bdhibernate_lasttp")
public class Lignematierefiliere implements java.io.Serializable {

	private LignematierefiliereId id;
	private Integer masseHoraire;

	public Lignematierefiliere() {
	}

	public Lignematierefiliere(LignematierefiliereId id) {
		this.id = id;
	}

	public Lignematierefiliere(LignematierefiliereId id, Integer masseHoraire) {
		this.id = id;
		this.masseHoraire = masseHoraire;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idMatiere", column = @Column(name = "idMatiere", nullable = false)),
			@AttributeOverride(name = "idFiliere", column = @Column(name = "idFiliere", nullable = false)),
			@AttributeOverride(name = "idMatfiliere", column = @Column(name = "idMatfiliere", nullable = false)) })
	public LignematierefiliereId getId() {
		return this.id;
	}

	public void setId(LignematierefiliereId id) {
		this.id = id;
	}

	@Column(name = "masseHoraire")
	public Integer getMasseHoraire() {
		return this.masseHoraire;
	}

	public void setMasseHoraire(Integer masseHoraire) {
		this.masseHoraire = masseHoraire;
	}

}
