package isamm.projet.beans;
// Generated 19 nov. 2017 22:25:43 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Matiere generated by hbm2java
 */
@Entity
@Table(name = "matiere", catalog = "bdhibernate_lasttp")
public class Matiere implements java.io.Serializable {

	private Integer idMatiere;
	private int idPersonne;
	private String code;
	private String libelle;

	public Matiere() {
	}

	public Matiere(int idPersonne) {
		this.idPersonne = idPersonne;
	}

	public Matiere(int idPersonne, String code, String libelle) {
		this.idPersonne = idPersonne;
		this.code = code;
		this.libelle = libelle;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMatiere", unique = true, nullable = false)
	public Integer getIdMatiere() {
		return this.idMatiere;
	}

	public void setIdMatiere(Integer idMatiere) {
		this.idMatiere = idMatiere;
	}

	@Column(name = "idPersonne", nullable = false)
	public int getIdPersonne() {
		return this.idPersonne;
	}

	public void setIdPersonne(int idPersonne) {
		this.idPersonne = idPersonne;
	}

	@Column(name = "code", length = 254)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libelle", length = 254)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
