package isamm.projet.beans;
// Generated 20 nov. 2017 01:22:30 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Matiere generated by hbm2java
 */
@Entity
@Table(name = "matiere", catalog = "bdhibernate_lasttp")
public class Matiere implements java.io.Serializable {

	private Integer idMatiere;
	private Formateur formateur;
	private String code;
	private String libelle;
	private Set<Lignematierefiliere> lignematierefilieres = new HashSet<Lignematierefiliere>(0);

	public Matiere() {
	}

	public Matiere(Formateur formateur) {
		this.formateur = formateur;
	}

	public Matiere(Formateur formateur, String code, String libelle, Set<Lignematierefiliere> lignematierefilieres) {
		this.formateur = formateur;
		this.code = code;
		this.libelle = libelle;
		this.lignematierefilieres = lignematierefilieres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMatiere", unique = true, nullable = false)
	public Integer getIdMatiere() {
		return this.idMatiere;
	}

	public void setIdMatiere(Integer idMatiere) {
		this.idMatiere = idMatiere;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPersonne", nullable = false)
	public Formateur getFormateur() {
		return this.formateur;
	}

	public void setFormateur(Formateur formateur) {
		this.formateur = formateur;
	}

	@Column(name = "code", length = 254)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libelle", length = 254)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "matiere")
	public Set<Lignematierefiliere> getLignematierefilieres() {
		return this.lignematierefilieres;
	}

	public void setLignematierefilieres(Set<Lignematierefiliere> lignematierefilieres) {
		this.lignematierefilieres = lignematierefilieres;
	}

}
